fields = [

 "SKU", 
 "Barcode", 
 "MPN", 
 "Product Title", 
 "Product Description", 
 "Variant Image", 
 "Image 2", 
 "Image 3", 
 "Image 4", 
 "Image 5", 
 "Image 6", 
 "Image 7", 
 "Image 8", 
 "Image 9", 
 "Image 10", 
 "Cost per item", 
 "Compare At Price", 
 "Price", 
 "Inventory Quantity", 
 "Entrenue qty available", 
 "Inventory Quantity", 
 "Fluid Oz", 
 "Vendor", 
 "Material", 
 "Color", 
 "Main Category", 
 "Sub-Category", 
 "Size", 
 "Fulfillment Service", 
 "Inventory tracked", 
 "Image URL", 
 "Variant Inventory Policy", 
 "Variant Fulfillment Service", 
 "Requires Shipping", 
 "Variant Requires Shipping"

]