# Generated by Django 6.0.1 on 2026-02-06 01:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('product_sync', 'Product Sync'), ('bulk_sync', 'Bulk Product Sync'), ('inventory_reconcile', 'Inventory Reconciliation'), ('order_import', 'Order Import')], help_text='Type of background job', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the job', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the job started execution', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job completed (success or failure)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the job was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the job was last updated')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'job_type'], name='api_job_status_e70db7_idx'), models.Index(fields=['-created_at'], name='api_job_created_653210_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this log entry was created')),
                ('message', models.TextField(help_text='Log message content')),
                ('job', models.ForeignKey(help_text='The job this log entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.job')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['job', 'timestamp'], name='api_joblog_job_id_585f9e_idx')],
            },
        ),
    ]
