# Generated by Django 6.0.1 on 2026-01-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_authentified',
            field=models.BooleanField(default=False),
        ),
    ]
