# Generated by Django 6.0.1 on 2026-01-30 16:17

import django.db.models.deletion
import shopify_models.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('sku', models.CharField(max_length=255, null=True)),
                ('tracked', models.BooleanField(default=True)),
                ('requires_shipping', models.BooleanField(default=False)),
                ('unit_cost_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('unit_cost_currency', models.CharField(max_length=3, null=True)),
                ('locations_count', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('activatable', models.BooleanField(default=False)),
                ('deactivatable', models.BooleanField(default=False)),
                ('deletable', models.BooleanField(default=False)),
                ('fulfills_online_orders', models.BooleanField(default=False)),
                ('has_active_inventory', models.BooleanField(default=False)),
                ('has_unfulfilled_orders', models.BooleanField(default=False)),
                ('ships_inventory', models.BooleanField(default=False)),
                ('address', models.JSONField(encoder=shopify_models.encoders.ShopifyDjangoJSONEncoder, null=True)),
                ('local_pickup_settings', models.JSONField(encoder=shopify_models.encoders.ShopifyDjangoJSONEncoder, null=True)),
                ('last_inventory_sync_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('body_html', models.TextField(default='', null=True)),
                ('handle', models.CharField(db_index=True, max_length=255)),
                ('product_type', models.CharField(db_index=True, max_length=255)),
                ('published_at', models.DateTimeField(null=True)),
                ('published_scope', models.CharField(default='global', max_length=64)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('template_suffix', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('vendor', models.CharField(db_index=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('quantities', models.JSONField(encoder=shopify_models.encoders.ShopifyDjangoJSONEncoder, null=True)),
                ('can_deactivate', models.BooleanField(default=False)),
                ('deactivation_alert', models.TextField(null=True)),
                ('scheduled_changes', models.JSONField(encoder=shopify_models.encoders.ShopifyDjangoJSONEncoder, null=True)),
                ('sync_pending', models.BooleanField(default=False)),
                ('source_updated_at', models.DateTimeField(null=True)),
                ('synced_at', models.DateTimeField(null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='shopify_models.inventoryitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.IntegerField(default=1, null=True)),
                ('src', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_models.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('barcode', models.CharField(max_length=255, null=True)),
                ('compare_at_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fulfillment_service', models.CharField(default='manual', max_length=32)),
                ('grams', models.IntegerField()),
                ('inventory_management', models.CharField(default='blank', max_length=32, null=True)),
                ('inventory_policy', models.CharField(default='deny', max_length=32, null=True)),
                ('inventory_quantity', models.IntegerField(null=True)),
                ('option1', models.CharField(max_length=255, null=True)),
                ('option2', models.CharField(max_length=255, null=True)),
                ('option3', models.CharField(max_length=255, null=True)),
                ('position', models.IntegerField(default=1, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_shipping', models.BooleanField(default=True)),
                ('sku', models.CharField(max_length=255, null=True)),
                ('taxable', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_models.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='variant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item', to='shopify_models.variant'),
        ),
    ]
