# Generated by Django 6.0.1 on 2026-02-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='body_html',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='published_scope',
        ),
        migrations.RemoveField(
            model_name='product',
            name='template_suffix',
        ),
    ]
