# Generated by Django 6.0.1 on 2026-02-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_models', '0002_rename_body_html_product_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='locations_count',
        ),
        migrations.RemoveField(
            model_name='inventorylevel',
            name='can_deactivate',
        ),
        migrations.RemoveField(
            model_name='inventorylevel',
            name='deactivation_alert',
        ),
        migrations.RemoveField(
            model_name='inventorylevel',
            name='scheduled_changes',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='inventory_quantity',
        ),
        migrations.AddField(
            model_name='inventorylevel',
            name='location_gid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='inventory_policy',
            field=models.CharField(choices=[('deny', 'Deny'), ('continue', 'Continue')], default='deny', max_length=32, null=True),
        ),
    ]
