# Generated by Django 6.0.1 on 2026-02-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_models', '0003_delete_location_remove_inventoryitem_locations_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='fulfillment_service',
        ),
    ]
