# Generated by Django 6.0.1 on 2026-02-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_models', '0004_remove_variant_fulfillment_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='sku',
            new_name='supplier_sku',
        ),
    ]
