# Generated by Django 6.0.1 on 2026-02-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_models', '0005_rename_sku_variant_supplier_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='sku',
            new_name='shopify_sku',
        ),
    ]
