# Generated by Django 6.0.1 on 2026-02-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_models', '0007_inventoryitem_source_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylevel',
            name='location_gid',
            field=models.CharField(default='gid://shopify/Location/89689161972', max_length=255),
        ),
    ]
