# Generated by Django 6.0.1 on 2026-02-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_models', '0011_alter_image_created_at_alter_image_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='map',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='msrp',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
