# Generated by Django 6.0.1 on 2026-02-06 01:14

import django.db.models.deletion
import shopify_models.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_models', '0012_variant_map_variant_msrp_variant_unit_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft')], default='ACTIVE', max_length=20)),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalogs',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(db_index=True, max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('primary', models.BooleanField(default=False)),
                ('currency', models.CharField(default='USD', max_length=3)),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('parent', models.JSONField(blank=True, encoder=shopify_models.encoders.ShopifyDjangoJSONEncoder, help_text='Relative adjustments to other prices (JSON format)', null=True)),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('auto_publish', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='catalogs',
            field=models.ManyToManyField(blank=True, help_text='Catalogs this product is published to', related_name='products', to='shopify_models.catalog'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='shopify_models.market'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='price_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='shopify_models.pricelist'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='publication',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='shopify_models.publication'),
        ),
    ]
