"""
Django settings for shop_manager project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jf9wq(65+d1v9xm(0@6reel6s18l)d+2#za^uebz8$an!mx41q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1',
                 '0.0.0.0', 'monkey-tight-lab.ngrok-free.app']

CSRF_TRUSTED_ORIGINS = ['https://monkey-tight-lab.ngrok-free.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'django_extensions',
    'jupyter',
    # 'shopify_auth',
    'rest_framework',
    'django_filters',

    # Local apps
    'core.apps.CoreConfig',
    'accounts.apps.AccountsConfig',
    'shopify_models.apps.ShopifyModelsConfig',
    'suppliers.apps.SuppliersConfig',
    'prices.apps.PricesConfig',  # Contextual pricing management
    'api.apps.ApiConfig',  # API for Shopify Polaris UI
    # 'shopify_webhook.apps.ShopifyWebhookConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'shopify_auth.session_tokens.middleware.SessionTokensAuthMiddleware',
    'api.middleware.SessionTokenMiddleware',  # Session token validation for API
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shop_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'shopify_auth.context_processors.shopify_auth'
            ],
        },
    },
]

WSGI_APPLICATION = 'shop_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


NOTEBOOK_ARGUMENTS = [
    '--ip', '0.0.0.0',
    '--port', '8888',
    '--NotebookApp.allow_origin="https://colab.research.google.com"',
    '--NotebookApp.port_retries=0',
    '--NotebookApp.allow_credentials=True',
    '--no-browser'
]
IPYTHON_KERNEL_DISPLAY_NAME = 'Django Kernel'

SHOPIFY_CLIENT_ID = os.environ.get("SHOPIFY_CLIENT_ID")
SHOPIFY_CLIENT_SECRET = os.environ.get("SHOPIFY_CLIENT_SECRET")
SHOPIFY_APP_SCOPES = os.environ.get("SHOPIFY_APP_SCOPES", "")
SHOPIFY_REDIRECT_URI = os.environ.get("SHOPIFY_REDIRECT_URI")
SHOPIFY_APP_NAME = 'shop_manager_app'
SHOP_ADMIN_URL = os.environ.get('SHOP_ADMIN_URL')
API_VERSION = os.environ.get("API_VERSION", "2025-10")
SHOPIFY_DEFAULT_LOCATION = os.environ.get("LOCATION", "gid://shopify/Location/89689161972")
SHOPIFY_FULFILLMENT_SERVICE = os.environ.get("FULFILLMENT_SERVICE", "manual")
PROVIDER_CURRENCY=os.environ.get("PROVIDER_CURRENCY")
INVENTORY_TRACKED=os.environ.get("INVENTORY_TRACKED", True)
DEBUG_INVENTORY_SYNC=os.environ.get("DEBUG_INVENTORY_SYNC", False)

LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO")
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(parents=True, exist_ok=True)

# Contextual Pricing Configuration
SHOPIFY_COUNTRY = os.environ.get("COUNTRY", "US")
SHOPIFY_PROVIDER_CODE = os.environ.get("PROVIDER_CODE", "NALPAC")
SHOPIFY_CATALOG_ID = os.environ.get("CATALOG_ID", None) or None
SHOPIFY_PRICE_LIST_ID = os.environ.get("PRICE_LIST_ID", None) or None

# Catalog name format: <COUNTRY>-<PROVIDER_CODE>
SHOPIFY_CATALOG_NAME = f"{SHOPIFY_COUNTRY}-{SHOPIFY_PROVIDER_CODE}"

# Currency mapping
CURRENCY_MAP = {
    'US': 'USD',
    'CA': 'CAD',
    'GB': 'GBP',
    'AU': 'AUD',
    'MX': 'MXN',
    'EU': 'EUR',
}
SHOPIFY_CURRENCY = CURRENCY_MAP.get(SHOPIFY_COUNTRY, 'USD')


# AUTHENTICATION_BACKENDS = ('shopify_auth.backends.ShopUserBackend',)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Use the accounts User model.
AUTH_USER_MODEL = 'accounts.User'
# SHOPIFY_AUTH_BOUNCE_PAGE_URL = '/accounts/login'
# SHOPIFY_APP_DEV_MODE = True

# Set the login redirect URL to the "home" page for your app (where to go after logging on).
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

# Set secure proxy header to allow proper detection of secure URLs behind a proxy.
# This ensures that correct 'https' URLs are generated when our Django app is running behind a proxy like nginx, or is
# being tunneled (by ngrok, for example).
# REST_FRAMEWORK = {"DEFAULT_AUTHENTICATION_CLASSES": ["shopify_auth.session_tokens.authentication.ShopifyTokenAuthentication"]}

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Authentication handled by middleware
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "django.log",
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "ERROR",
            "propagate": False,
        },
        "shopify_models": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "shop_manager": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
